library(plyr)
library(readr)
library(randomForest)
library(dplyr)
library(iptools)
library(jsonlite)
library(caret)
library(earth)
library(keras)
library(caTools)
library(RWeka)
library(kernlab)
library(e1071)
library(partykit)
library(ISLR)

data <- read.csv("data/RansomwareData.csv")
